# Generated by Django 5.2.7 on 2025-10-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="img")),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Electronics", "ELECTRONICS"),
                            ("Groceries", "GROCERIES"),
                            ("Clothings", "CLOTHING"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
